### PR TITLE
🐛 Fix scroll in sidebar and main view of cache

### PR DESCRIPTION
**Pull request by sagarhani**
This will fix scroll in #187 and also in sidebar.

### CODE REVIEW

**Comment by chip-miller** [comment]
Related: https://github.com/apollographql/apollo-client-devtools/pull/217

**Comment by tknickman** [comment]
Duplicates https://github.com/apollographql/apollo-client-devtools/pull/223

**Comment by dko-slapdash** [comment]
Both Chrome extension and GraphQL playground don't currently work, I just pulled the latest version. I hope merging this commit will fix both issues.

**Comment by slavanossar** [comment]
Also maybe consider replacing `overflow: scroll` with `overflow-y: auto` on `.inspector-sidebar`, so the scrollbar is only visible when needed.

**Comment by hwillson** [comment]
2.2.5 is now available in the Chrome store, and it includes this fix. Thanks!

**Pull request merged**
