### PR TITLE
fix scrolling issue on 2.2.3 in Chrome

### LINKED ISSUE #187: Can't scroll in Chrome
image

As screenshot above, I cannot scroll down in Apollo's tab.

### PR DESCRIPTION
**Pull request by bmviniciuss**
Fixes #187

### CODE REVIEW

**Comment by chip-miller** [comment]
Related: https://github.com/apollographql/apollo-client-devtools/pull/217

**Comment by stephenotalora** [comment]
can we get this merged?

**Comment by stephenotalora** [comment]
just following up on this.... for large data flowing throw an app this is really causing some issues it would be great if we could get this merged and resolved! @ducarroz @tknickman

**Comment by hwillson** [comment]
This should now be fixed in version 2.2.5, which is pending review in the Chrome store. It should be available in about an hour. Thanks!

**Pull request closed without merging**
