### PR TITLE
Prevent renovate from upgrading all-clients packages

### PR DESCRIPTION
**Pull request by jerelmiller**

### CODE REVIEW

**Review by alessbell — APPROVED** [review]
I think one more bad change snuck in with https://github.com/apollographql/apollo-client-devtools/pull/1294, lgtm

**Comment by jerelmiller** [comment]
Curse you renovate! Haha. I closed that one and renovate said "f it" and merged anyways

**Comment by alessbell** [comment]
> I closed that one and renovate said "f it" and merged anyways

I saw that happen in real time 😭

**Comment by phryneas** [comment]
I mean realistically it doesn't matter too much what happens with that package.json as it will just be recreated the next time we trigger the workflow

**Pull request merged**
