### PR TITLE
Merge tabRelay code with tab

### PR DESCRIPTION
**Pull request by jerelmiller**
The `tabRelay` module exported a promise that resolved with the tab relay. It appears this behavior [was relied on](https://github.com/apollographql/apollo-client-devtools/commit/727f019c72a1694af6a99bfedbe90454ba1ef8c5#diff-5827f053ef6026472ecfad62402ce9534ae9ddab0a1ddf31bcccec71f2b169e3L12-L32) at one point in time, but removed in https://github.com/apollographql/apollo-client-devtools/commit/727f019c72a1694af6a99bfedbe90454ba1ef8c5. There is no reason this code needs to be wrapped in a promise now that nothing awaits it, so this PR removes the wrapping promise.

### CODE REVIEW

**Review by phryneas — APPROVED** [review]
Nice, one less file :)

**Comment by jeremiah-snee-openx** [comment]
Not sure if this change is related but this issue seems to be happening again with the latest release. 
- https://github.com/apollographql/apollo-client-devtools/issues/868 

But this change moves code that was previously asynchronous and if failed would not have same impact on page being injected into

**Comment by jerelmiller** [comment]
@jeremiah-snee-openx hmmm.... not sure this is related since the `Promise` callback is executed synchronously.

```js
console.log('before');
new Promise(async () => console.log('inside'));
console.log('after');
```

yields

```
before
inside
after
```

It looks like there was some [code](https://github.com/apollographql/apollo-client-devtools/commit/727f019c72a1694af6a99bfedbe90454ba1ef8c5#diff-5827f053ef6026472ecfad62402ce9534ae9ddab0a1ddf31bcccec71f2b169e3L12) removed in https://github.com/apollographql/apollo-client-devtools/commit/727f019c72a1694af6a99bfedbe90454ba1ef8c5 that waited for the promise to resolve before executing other stuff. Since that code was removed, it seemed a bit silly to maintain the promise callback since it was already synchronous.

---

That being said, I definitely can reproduce this. We switched injection mechanisms in [3.8.0](https://github.com/apollographql/apollo-client-devtools/releases/tag/v4.8.0). This seems more likely, but still baffles me since the manual code injection is now only there for [firefox](https://github.com/apollographql/apollo-client-devtools/blob/d006308948b521ebdb15c960c4af8fc2b37f5b66/src/extension/tab/tab.ts#L21-L41).

React devtools also [uses this technique](https://github.com/facebook/react/blob/7d6f1e3c13686272c1d76813992d4e782fcb84e6/packages/react-devtools-extensions/src/background/executeScript.js#L5-L36), but those seem to execute ok.

By chance, do you know what version of the devtools you upgraded from (no worries if not since the auto updating makes it a bit difficult to know 😅)? I'll dig in a bit and see if I can find the source of what broke this. Appreciate you bringing this to our attention!

**Comment by jeremiah-snee-openx** [comment]
@jerelmiller your example looks synchronous because there is no delay inside the promise.

```js
const delay = ms => new Promise(res => setTimeout(res, ms));

console.log('before');
new Promise(async () => {
    await delay(200);
    console.log('inside')
});
console.log('after');
```

```
before
after
inside
```

**Comment by jerelmiller** [comment]
@jeremiah-snee-openx apologies I probably should have been a bit more explicit in my comment about how it relates to the change in this PR. The `await` in `tabRelay` didn't come until the [very end](https://github.com/apollographql/apollo-client-devtools/pull/1249/files#diff-0b388e5604e2f1dc10903aaa268984d99fd5eeff8b6e81edfab89813d536f1d5L23) of the promise callback, so all of the setup code above it ran synchronously up to that point. Your example has an `await` before the `console.log('inside')` so it makes sense that this is logged last. Since there was nothing in `tab.ts` that `awaited` the promise exported from `tabRelay`, the promise really wasn't doing anything here. Sure, there was some async code executed inside the promise callback but there really wasn't any logic after the `await` that mattered to anything.

Regardless, https://github.com/apollographql/apollo-client-devtools/pull/1261 fixed the real issue with the GCP console crash which was released in [4.8.2](https://github.com/apollographql/apollo-client-devtools/releases/tag/v4.8.2). If you are still seeing issues with the latest versions, please open a new issue and we'd be happy to look 🙂

**Pull request merged**
