### PR TITLE
Only inject `hook.js` script for Firefox. Use ExecutionWorld.MAIN for Chrome

### LINKED ISSUE #1162: Extension prevents websites (tested on atlassian.com) from loading styles
**Intended outcome:**
I was surfing the web trying to access the Atlassian website [atlassian.com](https://www.atlassian.com/). The website looks like the following when the extension is disabled or removed

Screenshot 2023-12-10 at 09 32 23

**Actual outcome:**
The website loads without styles 

Screenshot 2023-12-10 at 09 50 45

**How to reproduce the issue:**
Install or enable the extension then open  [atlassian.com](https://www.atlassian.com/)

**Desktop (please complete the following information):**

- OS: macOS Sonoma 14.0
- Browser: Arc Version 1.20.1 (43987), Brave v 1.61.101, Microsoft Edge Version 120.0.2210.61
- Extension version: Version 4.2.3

### PR DESCRIPTION
**Pull request by jerelmiller**
Fixes #1162

This is a revival of https://github.com/apollographql/apollo-client-devtools/pull/1164 with some tweaks. Now that we are running Chrome on Manifest v3, we are able to use `hook.js` as a content script using `ExecutionWorld.MAIN`. Unfortunately this is not yet supported in Firefox, so we have to rely on script injection for this to work. The script injection used in #1164 is now added back, but only when building for Firefox.

### CODE REVIEW

**Comment by phryneas** [comment]
This looks good to me, but I'm slightly concerned: didn't you see the extension break with the current Firefox code, in Firefox?

Could you reproduce that/

**Comment by jerelmiller** [comment]
Talked in our 1:1. Posting the answer here for transparency:

I feel a bit more confident now in this change for a couple reasons:
* We now unconditionally show the devtools where before we relied on a message sent to devtools before the panel was created (https://github.com/apollographql/apollo-client-devtools/pull/1220)
* Message passing has been reworked for stability (https://github.com/apollographql/apollo-client-devtools/pull/1226)
* The injection mechanism is now relegated to Firefox only now that Chrome is on manifest v3 (https://github.com/apollographql/apollo-client-devtools/pull/1225)

**Comment by jerelmiller** [comment]
Oops, didn't mean to close this.

**Comment by jerelmiller** [comment]
We are going to wait to merge this for a few days after [4.7.0](https://github.com/apollographql/apollo-client-devtools/pull/1235) goes out to ensure we catch any bugs or new issues that arise from that release.

**Comment by jerelmiller** [comment]
Putting in draft for now to avoid accidental merge until we are ready.

**Comment by jerelmiller** [comment]
So far we've seen no reports that the latest update caused any more issues. I'll go ahead and merge this and get a release out tomorrow.

**Pull request merged**
