### PR TITLE
support 2.0 and upgrade to react-16

### PR DESCRIPTION
**Pull request by jbaxleyiii**
This updates the dev tools to support Apollo Client 2.0 (requires apollo-client 1.* or ^2.0.0-rc.2)

### CODE REVIEW

**Comment by peggyrayzis** [comment]
Just tested with Githunt. Queries, mutations, and the store look good to go, but for some reason, GraphiQL is showing schema not found. If you try to run a query, no data comes back. 😢 

githunt

**Comment by jbaxleyiii** [comment]
@ramyanaga would you be able to take a look at this as well?

**Comment by ramyanaga** [comment]
It looks good to me! Also tested it against githunt, and didn't run into the error Peggy was getting

**Comment by glasser** [comment]
FWIW I'm getting the error Peggy saw. I filed it as #81.

**Pull request merged**
