### PR TITLE
Fix to enable scroll of "explorer" sidebar

### LINKED ISSUE #214: Can't scroll in Apollo dev tool's explore in react-native-debugger
After updating to 0.9.9, the explorer field is added to Apollo which is awesome, however if the list is too long you can scroll down to see the rest of the queries.
image

### PR DESCRIPTION
**Pull request by RIP21**
Fixes #214

### CODE REVIEW

**Comment by chip-miller** [comment]
:shipit: C'mon.... all the cool kids are doing it. https://contribute.meteor.com

**Comment by RIP21** [comment]
I did it :)

**Comment by qeternity** [comment]
This really needs to be merged. Cache is completely unusable without this fix. Not sure how this isn't affecting more people.

**Comment by RIP21** [comment]
@qeternity +1. It's extremely annoying without it.

**Comment by chip-miller** [comment]
It's been over a month for a (super helpful) 1-line fix. 
@hwillson - Is this still an active project?

**Comment by hwillson** [comment]
Sorry for the delay all - I haven't been as involved here lately as I would like (love) to be. I'll see if I can get this in and pushed out tonight. Thanks!

**Comment by hwillson** [comment]
Version 2.2.4 should now be available for Chrome with this fix.

**Comment by chip-miller** [comment]
Thanks @hwillson!

**Comment by brent-williams** [comment]
Still broken with Chromium 76.0.3809.100 and Apollo Client Dev Tools 2.2.4.

**Comment by StefanFeederle** [comment]
I can confirm it's still an issue with 2.2.4.
@hwillson please help us ;)

**Comment by dusty** [comment]
I'm also unable to scroll cache with 2.2.4 and Chrome 76.0.3809.132.

**Comment by RageOfJustice** [comment]
Still an issue in react-native-debugger

**Pull request merged**
