### PR TITLE
making update data interval larger

### PR DESCRIPTION
**Pull request by tnrich**
This hopefully serves as a temporary fix to issue https://github.com/apollographql/apollo-client-devtools/issues/28

### CODE REVIEW

**Comment by rrdelaney** [comment]
Hey, thanks so much for submitting this PR! I'm currently working on making the devtools push based (https://github.com/apollographql/apollo-client-devtools/pull/43) but it seems like that's going to go slowly 😕 In the mean time, this looks like a solid fix!

I'll check this out and see if it has any noticeable impact on load times. if not this looks good to go!

**Comment by stubailo** [comment]
Do we have an idea of a good interval for now? We bumped it to 1000, does it really need to go up to 5000? Of course, push based is the right approach long term.

**Comment by tnrich** [comment]
@stubailo , my PR actually bumped it to 5000, but maybe 10000 would be better? It is seemingly a bit arbitrary

**Comment by stubailo** [comment]
`1000` not `10000`. But I think `5000` is super long because then the store will only update every 5 seconds?

**Comment by tnrich** [comment]
Oh, whoops you're right @stubailo

**Comment by stubailo** [comment]
Which panels are you using? Are you using the store panel? What do you use it for

**Comment by tnrich** [comment]
Ahh @stubailo , I don't use the store panel very much because I can view the store in the redux devtools already. I only really look at the watched queries panel (and now watched mutation panel!).

**Comment by stubailo** [comment]
Ah - in that case, this interval shouldn't change anything since this is just the refresh for the store panel. That explains why the refresh didn't make it laggy.

Unless somehow we are polling for store changes all the time.

**Comment by thomassuckow** [comment]
Would probably be better to do something like #51

**Pull request closed without merging**
